spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/astor_test
    username: testuser
    password: testpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    enabled: true
