spring:
  telegram:
    oauth:
      client-id: ${TELEGRAM_CLIENT_ID}
      client-secret: ${TELEGRAM_CLIENT_SECRET}
      redirect-uri: ${TELEGRAM_REDIRECT_URI}
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
      change-log: ${LIQUIBASE_CHANGELOG}
      enabled: true